[package]
name = "complexity-exercise-1-4"
description = "Program to execute a given DFA, NFA or regex over a given word, or convert regex to NFA, NFA to DFA"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
