[package]
name = "complexity-exercise-1-4"
description = "Program to execute a given DFA over a given word"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
